# Generated by Django 4.2 on 2023-04-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_image_rmbg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(upload_to='upload/images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='rmbg_img',
            field=models.ImageField(blank=True, upload_to='upload/rmbg_img/'),
        ),
    ]
