# Generated by Django 4.2 on 2023-04-10 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_image_img_alter_image_rmbg_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='created_at',
        ),
    ]
