# Generated by Django 4.2 on 2023-04-10 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_image_img_alter_image_rmbg_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='image',
        ),
    ]
