# Generated by Django 4.2 on 2023-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_image_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.FilePathField(path='/static/image'),
        ),
    ]
